version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devsecops_be_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - devsecops_be_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: devsecops_be_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - devsecops_be_network

volumes:
  postgres_data:

networks:
  devsecops_be_network:
    driver: bridge
